language: ruby

rvm:
- 2.3.1

bundler_args: --without production

script:
- bin/rake db:setup RAILS_ENV=test
- bin/rake db:migrate RAILS_ENV=test
- bin/rake
- bundle install
- bundle exec rspec

cache: bundler

services:
- postgresql

addons:
  postgresql: "9.4"

notifications:
    slack: jd8112:k0zDEsRj4v33kz1p6JcIFFyv
